FROM centos-deploy-base

RUN echo root:root | chpasswd
RUN : > /etc/fstab

RUN yum -y install \
	kernel \
	grub2-pc \
	e2fsprogs \
	syslinux-extlinux \
	NetworkManager \
	iproute \
	less \
	newt \
	rsync \
	openssh-clients \
	openssh-server \
	&& yum clean all
